on: push
name: Tests CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      postgres:
        image: postgres:12.9
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1111
          POSTGRES_DB: testdb
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: make install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Connect to PostgreSQL
      run: node client.js
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
    - name: Run Tests
      run: make test



