on: push
name: Tests CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    env:
      DB_HOST: postgres
    
    services:
      postgres:
        image: postgres:latest
        env:
          DB_DATABASE: postgres        
          DB_PASSWORD: postgres
          DB_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Setup project
      run: make setup

    - name: Run Tests
      run: make test



